from tensorflow/tensorflow:2.16.1-gpu-jupyter

run apt-get update && apt-get install -y graphviz

copy requirements.txt .

run pip install --upgrade pip && pip install -r requirements.txt
# for plotting model


